# Generated by Django 2.0 on 2021-11-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phno', models.CharField(max_length=12)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('dept_head', 'department head'), ('staff', 'staffs')], default='staff', max_length=20)),
            ],
        ),
    ]
