# Generated by Django 3.2.9 on 2021-11-15 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='relation_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.CharField(choices=[('all', 'All'), ('dept_trust', 'Departments under a trust'), ('dept_staff', 'Departmental staff'), ('self', 'Self')], default='all', max_length=20)),
                ('trustee', models.CharField(choices=[('all', 'All'), ('dept_trust', 'Departments under a trust'), ('dept_staff', 'Departmental staff'), ('self', 'Self')], default='dept_trust', max_length=20)),
                ('dept_head', models.CharField(choices=[('all', 'All'), ('dept_trust', 'Departments under a trust'), ('dept_staff', 'Departmental staff'), ('self', 'Self')], default='dept_staff', max_length=20)),
                ('staff', models.CharField(choices=[('all', 'All'), ('dept_trust', 'Departments under a trust'), ('dept_staff', 'Departmental staff'), ('self', 'Self')], default='self', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='trust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phno', models.CharField(max_length=10, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('trustee', 'Trustee'), ('dept_head', 'Head of Department'), ('staff', 'Staff')], default='staff', max_length=20)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact_details.department')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='trust',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact_details.trust'),
        ),
    ]
