# Generated by Django 3.2.9 on 2021-12-03 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation_table',
            name='location_admin',
            field=models.CharField(choices=[('all', 'All'), ('dept_trust', 'Departments under a trust'), ('dept_staff', 'Departmental staff'), ('self', 'Self'), ('loc_depts', 'Departments under a location')], default='loc_depts', max_length=20),
        ),
        migrations.AlterField(
            model_name='relation_table',
            name='admin',
            field=models.CharField(choices=[('all', 'All'), ('dept_trust', 'Departments under a trust'), ('dept_staff', 'Departmental staff'), ('self', 'Self'), ('loc_depts', 'Departments under a location')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='relation_table',
            name='dept_head',
            field=models.CharField(choices=[('all', 'All'), ('dept_trust', 'Departments under a trust'), ('dept_staff', 'Departmental staff'), ('self', 'Self'), ('loc_depts', 'Departments under a location')], default='dept_staff', max_length=20),
        ),
        migrations.AlterField(
            model_name='relation_table',
            name='staff',
            field=models.CharField(choices=[('all', 'All'), ('dept_trust', 'Departments under a trust'), ('dept_staff', 'Departmental staff'), ('self', 'Self'), ('loc_depts', 'Departments under a location')], default='self', max_length=20),
        ),
        migrations.AlterField(
            model_name='relation_table',
            name='trustee',
            field=models.CharField(choices=[('all', 'All'), ('dept_trust', 'Departments under a trust'), ('dept_staff', 'Departmental staff'), ('self', 'Self'), ('loc_depts', 'Departments under a location')], default='dept_trust', max_length=20),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('trustee', 'Trustee'), ('dept_head', 'Head of Department'), ('staff', 'Staff'), ('location_admin', 'Location Admin')], default='staff', max_length=20),
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trust', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact_details.trust')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact_details.location'),
        ),
        migrations.AddField(
            model_name='user_detail',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact_details.location'),
        ),
    ]
