# Generated by Django 2.0 on 2021-11-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('dept_head', 'Department head'), ('staff', 'Staff')], default='staff', max_length=20),
        ),
    ]
