# Generated by Django 2.0 on 2021-11-08 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_details', '0002_auto_20211108_2302'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user_detail',
            table='User Detail',
        ),
    ]
