# Generated by Django 3.2.9 on 2021-11-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_details', '0003_auto_20211108_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='department',
            field=models.CharField(choices=[('kitchen', 'Kitchen'), ('goshala', 'Goshala')], default='kitchen', max_length=100),
        ),
    ]
