# Generated by Django 3.2.9 on 2021-11-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_details', '0004_user_detail_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='department',
            field=models.CharField(choices=[('admin', 'Admin'), ('kitchen', 'Kitchen'), ('goshala', 'Goshala')], default='kitchen', max_length=100),
        ),
    ]
